config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users do
    resources :statuses
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get root to: 'users#home'
  get '/home', to: 'users#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/login', to: 'sessions#create'
  patch '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get '/users/:id/follow', to: 'users#follow'
  get 'users/:id/unfollow', to: 'users#unfollow'
end

app/controllers/statuses_controller.rb
# frozen_string_literal: true

class StatusesController < ApplicationController
  before_action :set_user, :authenticate_user, :current_user
  before_action :set_status, only: %i[show edit update destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = @user.statuses.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show; end

  # GET /statuses/new
  def new
    @status = @user.statuses.build
  end

  # GET /statuses/1/edit
  def edit
    render 'index' if @current_user.id != @user.id
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = @user.statuses.build(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to user_status_path(@user, @status), notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: user_status_path(@user, @status) }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    if @current_user.id != @user.id
      render 'index'
    else
      respond_to do |format|
        if @status.update(status_params)
          format.html { redirect_to user_status_path(@user, @status), notice: 'Status was successfully updated.' }
          format.json { render :show, status: :ok, location: user_status_path(@user, @status) }
        else
          format.html { render :edit }
          format.json { render json: @status.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    if @current_user.id != @user.id
      render 'index'
    else
      @status.destroy
      respond_to do |format|
        format.html { redirect_to user_statuses_path(@user), notice: 'Status was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_status
    @status = Status.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def status_params
    params.require(:status).permit(:content)
  end
end

app/helpers/statuses_helper.rb
# frozen_string_literal: true

module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= form_with model: [user, status] do |form| %>
  <% if status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
        <% status.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form', status: @status, user: @user %>

<%= link_to 'Show', user_status_path(@user, @status) %> |
<%= link_to 'Back', user_statuses_path(@user) %>

app/views/statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Statuses</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.user %></td>
        <td><%= status.content %></td>
        <td><%= link_to 'Show', user_status_path(@user, status) %></td>
        <td><%= link_to 'Edit', edit_user_status_path(@user, status) %></td>
        <td><%= link_to 'Destroy', user_status_path(@user, status), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status', new_user_status_path(@user) %>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form', status: @status, user: @user %>

<%= link_to 'Back', user_statuses_path(@user) %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @status.user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @status.user.last_name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<a class="btn btn-primary" href= <%= edit_user_status_path(@user, @status) %> role="button">Edit </a>